# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Better Tomorrow with Computer Science"
default_author:     "Insu Jang"

author:
#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
  github:           insujang
#  stackoverflow:    your-id
#  quora:            your-id
  linkedin:         insujang
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
  email:            insujang@calab.kaist.ac.kr

copyright:
  year:             2017
  name:             Insu Jang

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "insujang"

# URL
url:                "https://insujang.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           7
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/insujang"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

collections:
  protected:
    output:         false
    permalink: "/protecteduic2ws/:year-:month-:day/:title/"

markdown: kramdown
highlighter: rouge

kramdown:
  input:    GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:            [vendor]
